const data = {
  products: [
    {
      name: 'Nike Slim Shirt',
      slug: 'Nike-Slim-Shirt',
      category: 'Shirts',
      image: 'images/p1.jpg',
      price: 120,
      countInSock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality shirt ',
    },
    {
      name: 'Adidas Fit Shirt',
      slug: 'Adidas-Fit-Shirt',
      category: 'Shirts',
      image: 'images/p2.jpg',
      price: 250,
      countInSock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality shirt ',
    },
    {
      name: 'Nike Slim Pant',
      slug: 'Nike-Slim-Pant',
      category: 'Pantss',
      image: 'images/p3.jpg',
      price: 25,
      countInSock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'High quality shirt ',
    },
    {
      name: 'Nike Fit Shirt',
      slug: 'Nike-Fit-Shirt',
      category: 'Pants',
      image: 'images/p4.jpg',
      price: 65,
      countInSock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality shirt ',
    },
  ],
};
